name: Update App Config

on:
  workflow_dispatch:
    inputs:
      package_prefix:
        description: 'New package prefix (e.g., org.example)'
        required: true
        type: string
      package_name:
        description: 'New package name (e.g., app)'
        required: true
        type: string
      app_name:
        description: 'New app display name (e.g., MyApp)'
        required: true
        type: string

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required to push commits later

      - name: Ensure workflow is run in a fork
        if: github.repository == 'YourOrg/YourRepo'
        run: |
          echo "This workflow cannot run on the main repo. Please use a fork."
          exit 1

      - name: Set up Kotlin
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Kotlin compiler
        run: sudo apt-get install -y kotlin

      - name: Show full package
        run: |
          echo "Full package will be: ${GITHUB_EVENT_INPUT_PACKAGE_PREFIX}.${GITHUB_EVENT_INPUT_PACKAGE_NAME}"

      - name: Run updateAppConfig.kts
        run: |
          kotlinc -script updateAppConfig.kts \
            "${{ github.event.inputs.package_prefix }}" \
            "${{ github.event.inputs.package_name }}" \
            "${{ github.event.inputs.app_name }}"

      - name: Clean build
        run: ./gradlew clean build --no-daemon

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update app config via workflow"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
